POST http://localhost/api/student HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 12|KxpUDMUSmKVft2mOtW3nPiK7ri3R7ZTg81qLcEgU

    {   
        "name": "Test Student",
        "email": "email2@email.com",
    }

###

POST http://localhost/api/login HTTP/1.1
content-type: application/json
Accept: application/json

    {   
        "email": "admin@admin.com",
        "password": "password"
    }
###

GET http://localhost/api/logout HTTP/1.1
Accept: application/json
Authorization: Bearer 5|00stNiNA9RJdX1xWCNKjNj7vrYLkZW7EfsUwpleP

###


POST http://localhost/api/me HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer 5|00stNiNA9RJdX1xWCNKjNj7vrYLkZW7EfsUwpleP


